language: ruby
rvm:
    - 1.9.3
script: rake ci
env:
    - CLANG_VERSION="3.4"
    - CLANG_VERSION="3.5"
install:
    - sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-${CLANG_VERSION} main' >> /etc/apt/sources.list"
    - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
    - sudo apt-get -qq update
    - sudo apt-get -qq --force-yes install clang-format-${CLANG_VERSION}
    - bundle install
    - clang-format-${CLANG_VERSION} -version || true
